// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tameenk.Identity.Log.DAL;

namespace Tameenk.Identity.Log.DAL.Migrations
{
    [DbContext(typeof(LogContext))]
    [Migration("20200415123655_create")]
    partial class create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tameenk.Identity.Log.DAL.AuthenticationLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Channel");

                    b.Property<string>("CompanyCrNumber");

                    b.Property<string>("CompanyName");

                    b.Property<string>("CompanySponserId");

                    b.Property<string>("CompanyVatNumber");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email");

                    b.Property<int>("ErrorCode");

                    b.Property<string>("ErrorDescription");

                    b.Property<string>("Method");

                    b.Property<string>("Password");

                    b.Property<string>("ServerIP");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("AuthenticationLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
